rules:
    attribute-quotes: 2
    border-zero: 2
    indentation:
        - 2
        - size: 4
    mixins-before-declarations: 2
    nesting-depth:
        - 2
        - max-depth: 3
    no-mergeable-selectors: 2
    no-trailing-whitespace: 2
    pseudo-element: 2
    quotes: 2
    space-after-colon: 2
    space-after-comma: 2
    space-around-operator: 2
    space-before-brace: 2
    space-between-parens: 2
    trailing-semicolon: 2
    url-quotes: 2

    # turned off
    class-name-format: 0
    empty-args: 0
    empty-line-between-blocks: 0
    final-newline: 0
    force-attribute-nesting: 0
    force-element-nesting: 0
    force-pseudo-nesting: 0
    hex-length: 0
    hex-notation: 0
    leading-zero: 0
    no-color-keywords: 0
    no-css-comments: 0
    no-duplicate-properties: 0
    no-qualifying-elements: 0
    no-url-domains: 0
    no-url-protocols: 0
    no-vendor-prefixes: 0
    property-sort-order: 0
    single-line-per-selector: 0
    variable-name-format: 0
