env:
  browser: true
  commonjs: true
  es6: true
  node: true
extends: 'eslint:recommended'
overrides:
  files: ['src/app/js/**/*.js', 'src/app/js/*.js']
  excludedFiles: 'src/app/js/vendor/'
parserOptions:
  ecmaFeatures:
    experimentalObjectRestSpread: true
    jsx: true
  sourceType: module
plugins:
  - react
rules:
  indent:
    - error
    - 4
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
  no-console: 0
